// ~~ Generated by projen. To modify, edit .projenrc.ts and run "npx projen".
import * as path from 'path';
import * as lambda from 'aws-cdk-lib/aws-lambda';
import { Construct } from 'constructs';

/**
 * Props for MailFunction
 */
export interface MailFunctionProps extends lambda.FunctionOptions {
}

/**
 * An AWS Lambda function which executes src/submission-forwarder/mail-lambda/mail.
 */
export class MailFunction extends lambda.Function {
  constructor(scope: Construct, id: string, props?: MailFunctionProps) {
    super(scope, id, {
      description: 'src/submission-forwarder/mail-lambda/mail.lambda.ts',
      ...props,
      runtime: new lambda.Runtime('nodejs20.x', lambda.RuntimeFamily.NODEJS),
      handler: 'index.handler',
      code: lambda.Code.fromAsset(path.join(__dirname, '../../../assets/submission-forwarder/mail-lambda/mail.lambda')),
    });
    this.addEnvironment('AWS_NODEJS_CONNECTION_REUSE_ENABLED', '1', { removeInEdge: true });
  }
}