// ~~ Generated by projen. To modify, edit .projenrc.ts and run "npx projen".
import * as path from 'path';
import * as lambda from 'aws-cdk-lib/aws-lambda';
import { Construct } from 'constructs';

/**
 * Props for DocumentsToS3StorageFunction
 */
export interface DocumentsToS3StorageFunctionProps extends lambda.FunctionOptions {
}

/**
 * An AWS Lambda function which executes src/submission-forwarder/documentsToS3Storage/documentsToS3Storage.
 */
export class DocumentsToS3StorageFunction extends lambda.Function {
  constructor(scope: Construct, id: string, props?: DocumentsToS3StorageFunctionProps) {
    super(scope, id, {
      description: 'src/submission-forwarder/documentsToS3Storage/documentsToS3Storage.lambda.ts',
      ...props,
      runtime: new lambda.Runtime('nodejs22.x', lambda.RuntimeFamily.NODEJS),
      handler: 'index.handler',
      code: lambda.Code.fromAsset(path.join(__dirname, '../../../assets/submission-forwarder/documentsToS3Storage/documentsToS3Storage.lambda')),
    });
    this.addEnvironment('AWS_NODEJS_CONNECTION_REUSE_ENABLED', '1', { removeInEdge: true });
  }
}