// ~~ Generated by projen. To modify, edit .projenrc.ts and run "npx projen".
import * as path from 'path';
import * as lambda from 'aws-cdk-lib/aws-lambda';
import { Construct } from 'constructs';

/**
 * Props for LoginMockFunction
 */
export interface LoginMockFunctionProps extends lambda.FunctionOptions {
}

/**
 * An AWS Lambda function which executes src/static-form-definitions/formio-login/login-mock.
 */
export class LoginMockFunction extends lambda.Function {
  constructor(scope: Construct, id: string, props?: LoginMockFunctionProps) {
    super(scope, id, {
      description: 'src/static-form-definitions/formio-login/login-mock.lambda.ts',
      ...props,
      runtime: new lambda.Runtime('nodejs24.x', lambda.RuntimeFamily.NODEJS),
      handler: 'index.handler',
      code: lambda.Code.fromAsset(path.join(__dirname, '../../../assets/static-form-definitions/formio-login/login-mock.lambda')),
    });
    this.addEnvironment('AWS_NODEJS_CONNECTION_REUSE_ENABLED', '1', { removeInEdge: true });
  }
}