// ~~ Generated by projen. To modify, edit .projenrc.ts and run "npx projen".
import * as path from 'path';
import * as lambda from 'aws-cdk-lib/aws-lambda';
import { Construct } from 'constructs';

/**
 * Props for ReceiverMonitoringFunction
 */
export interface ReceiverMonitoringFunctionProps extends lambda.FunctionOptions {
}

/**
 * An AWS Lambda function which executes src/receiver-monitoring/lambda/ReceiverMonitoring.
 */
export class ReceiverMonitoringFunction extends lambda.Function {
  constructor(scope: Construct, id: string, props?: ReceiverMonitoringFunctionProps) {
    super(scope, id, {
      description: 'src/receiver-monitoring/lambda/ReceiverMonitoring.lambda.ts',
      ...props,
      runtime: new lambda.Runtime('nodejs24.x', lambda.RuntimeFamily.NODEJS),
      handler: 'index.handler',
      code: lambda.Code.fromAsset(path.join(__dirname, '../../../assets/receiver-monitoring/lambda/ReceiverMonitoring.lambda')),
    });
    this.addEnvironment('AWS_NODEJS_CONNECTION_REUSE_ENABLED', '1', { removeInEdge: true });
  }
}