// ~~ Generated by projen. To modify, edit .projenrc.ts and run "npx projen".
import * as path from 'path';
import * as lambda from 'aws-cdk-lib/aws-lambda';
import { Construct } from 'constructs';

/**
 * Props for StandplaatsvergunningFunction
 */
export interface StandplaatsvergunningFunctionProps extends lambda.FunctionOptions {
}

/**
 * An AWS Lambda function which executes src/api/form-prefill/standplaatsvergunning/standplaatsvergunning.
 */
export class StandplaatsvergunningFunction extends lambda.Function {
  constructor(scope: Construct, id: string, props?: StandplaatsvergunningFunctionProps) {
    super(scope, id, {
      description: 'src/api/form-prefill/standplaatsvergunning/standplaatsvergunning.lambda.ts',
      ...props,
      runtime: new lambda.Runtime('nodejs24.x', lambda.RuntimeFamily.NODEJS),
      handler: 'index.handler',
      code: lambda.Code.fromAsset(path.join(__dirname, '../../../../assets/api/form-prefill/standplaatsvergunning/standplaatsvergunning.lambda')),
    });
    this.addEnvironment('AWS_NODEJS_CONNECTION_REUSE_ENABLED', '1', { removeInEdge: true });
  }
}